// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Omar_Ahmed_0523006.Data;

#nullable disable

namespace Omar_Ahmed_0523006.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251020073724_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Omar_Ahmed_0523006.Data.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpYears")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speclatation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamID")
                        .IsUnique();

                    b.ToTable("coaches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpYears = 2,
                            Name = "omar",
                            Speclatation = "puching",
                            TeamID = 1
                        },
                        new
                        {
                            Id = 2,
                            ExpYears = 32,
                            Name = "omarAhmed",
                            Speclatation = "helping",
                            TeamID = 2
                        },
                        new
                        {
                            Id = 3,
                            ExpYears = 22,
                            Name = "omarAhmedSamy",
                            Speclatation = "Feeling",
                            TeamID = 3
                        },
                        new
                        {
                            Id = 4,
                            ExpYears = 67,
                            Name = "omarAghmedSamyMohamed",
                            Speclatation = "hitting",
                            TeamID = 4
                        });
                });

            modelBuilder.Entity("Omar_Ahmed_0523006.Data.Models.Compttion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateComp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Locatioon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("compttion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateComp = new DateTime(2005, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Locatioon = "al_hdayk al_qopa",
                            Titel = "WorldCup1"
                        },
                        new
                        {
                            Id = 2,
                            DateComp = new DateTime(2005, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Locatioon = "al_hdayk al_qopa",
                            Titel = "WorldCup2"
                        },
                        new
                        {
                            Id = 3,
                            DateComp = new DateTime(2005, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Locatioon = "al_hdayk al_qopa",
                            Titel = "WorldCup3"
                        },
                        new
                        {
                            Id = 4,
                            DateComp = new DateTime(2005, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Locatioon = "al_hdayk al_qopa",
                            Titel = "WorldCup4"
                        });
                });

            modelBuilder.Entity("Omar_Ahmed_0523006.Data.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("team");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "last",
                            Name = "Manchester"
                        },
                        new
                        {
                            Id = 2,
                            City = "lastOflast",
                            Name = "Man"
                        },
                        new
                        {
                            Id = 3,
                            City = "lastOfoflast",
                            Name = "chester"
                        },
                        new
                        {
                            Id = 4,
                            City = "lastofofoflast",
                            Name = "misy"
                        });
                });

            modelBuilder.Entity("Omar_Ahmed_0523006.Data.Models.TeamCompttion", b =>
                {
                    b.Property<int>("CompttionId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("CompttionId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("teamCompttions");

                    b.HasData(
                        new
                        {
                            CompttionId = 2,
                            TeamId = 1
                        },
                        new
                        {
                            CompttionId = 4,
                            TeamId = 3
                        },
                        new
                        {
                            CompttionId = 3,
                            TeamId = 2
                        },
                        new
                        {
                            CompttionId = 1,
                            TeamId = 4
                        });
                });

            modelBuilder.Entity("Omar_Ahmed_0523006.Data.Models.player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("player");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 42,
                            FullName = "ahmed",
                            Postion = "mid",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 60,
                            FullName = "Salah",
                            Postion = "Attaker",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 22,
                            FullName = "ziad",
                            Postion = "Defender",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            Age = 33,
                            FullName = "Mohamed",
                            Postion = "Defender",
                            TeamId = 1
                        });
                });

            modelBuilder.Entity("Omar_Ahmed_0523006.Data.Models.Coach", b =>
                {
                    b.HasOne("Omar_Ahmed_0523006.Data.Models.Team", "Team")
                        .WithOne("Coach")
                        .HasForeignKey("Omar_Ahmed_0523006.Data.Models.Coach", "TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Omar_Ahmed_0523006.Data.Models.TeamCompttion", b =>
                {
                    b.HasOne("Omar_Ahmed_0523006.Data.Models.Compttion", "Compttion")
                        .WithMany("teamCompttions")
                        .HasForeignKey("CompttionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omar_Ahmed_0523006.Data.Models.Team", "Team")
                        .WithMany("teamCompttions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compttion");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Omar_Ahmed_0523006.Data.Models.player", b =>
                {
                    b.HasOne("Omar_Ahmed_0523006.Data.Models.Team", "team")
                        .WithMany("players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("team");
                });

            modelBuilder.Entity("Omar_Ahmed_0523006.Data.Models.Compttion", b =>
                {
                    b.Navigation("teamCompttions");
                });

            modelBuilder.Entity("Omar_Ahmed_0523006.Data.Models.Team", b =>
                {
                    b.Navigation("Coach")
                        .IsRequired();

                    b.Navigation("players");

                    b.Navigation("teamCompttions");
                });
#pragma warning restore 612, 618
        }
    }
}
